[package]
name = "dekyx-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
zkfmi-crypto.workspace = true
curve25519-dalek.workspace = true
ed25519-dalek.workspace = true
rand_core.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true


[dev-dependencies]
zkfmi-crypto = { workspace = true, features = ["test-support"] }
serde_json.workspace = true
